apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prospectf500-app1-dev

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

images:
  - name: prospectf500-app1-backend
    newName: ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/prospectf500-app1-backend
    newTag: latest
  - name: prospectf500-app1-frontend
    newName: ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/prospectf500-app1-frontend
    newTag: latest
