apiVersion: v1
kind: Service
metadata:
  name: speri-008-backend
  labels:
    app: speri-008-backend
    tenant: speri
    app-identifier: speri-008
    environment: dev
    managed-by: opsera-gitops
spec:
  type: ClusterIP
  selector:
    app: speri-008-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
