apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ramya-dev

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

commonLabels:
  tenant: adlcteam
  app-identifier: ramya
  environment: dev
  deployment-name: ramya-opsera
  managed-by: opsera-gitops
  created-by: claude-code

