apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base




images:
  - name: PLACEHOLDER_ECR_BACKEND
    newName: 792373136340.dkr.ecr.ap-south-1.amazonaws.com/opsera-se/your-username-backend
    newTag: "497148355a58e21da031ff811a5ecb312af2f473"
  - name: PLACEHOLDER_ECR_FRONTEND
    newName: 792373136340.dkr.ecr.ap-south-1.amazonaws.com/opsera-se/your-username-frontend
    newTag: "497148355a58e21da031ff811a5ecb312af2f473"
