apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base






images:
  - name: PLACEHOLDER_ECR_BACKEND
    newName: 792373136340.dkr.ecr.ap-south-1.amazonaws.com/opsera-se/your-username-backend
    newTag: "5540feaa4f96865ab192d85297ef2d90126868b5"
  - name: PLACEHOLDER_ECR_FRONTEND
    newName: 792373136340.dkr.ecr.ap-south-1.amazonaws.com/opsera-se/your-username-frontend
    newTag: "5540feaa4f96865ab192d85297ef2d90126868b5"
