apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base

images:
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-backend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-backend
    newTag: "c67951e9fd14067ce6252bfcf027301e8a7c58af"
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-frontend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-frontend
    newTag: "c67951e9fd14067ce6252bfcf027301e8a7c58af"
