apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base

images:
  - name: PLACEHOLDER_ECR_BACKEND
    newName: PLACEHOLDER_ECR_BACKEND
    newTag: latest
  - name: PLACEHOLDER_ECR_FRONTEND
    newName: PLACEHOLDER_ECR_FRONTEND
    newTag: latest
