apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base

images:
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-backend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-backend
    newTag: "51a04f819a86b3048abe9c9153efa704690052f5"
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-frontend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-frontend
    newTag: "51a04f819a86b3048abe9c9153efa704690052f5"
