apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base



images:
  - name: PLACEHOLDER_ECR_BACKEND
    newName: 792373136340.dkr.ecr.ap-south-1.amazonaws.com/opsera-se/your-username-backend
    newTag: "36c01a7992a7342ce419297873f0828992987dca"
  - name: PLACEHOLDER_ECR_FRONTEND
    newName: 792373136340.dkr.ecr.ap-south-1.amazonaws.com/opsera-se/your-username-frontend
    newTag: "36c01a7992a7342ce419297873f0828992987dca"
