apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base







images:
  - name: PLACEHOLDER_ECR_BACKEND
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-backend
    newTag: "9fbc08eb204a503b56f76e249f95e080b844413d"
  - name: PLACEHOLDER_ECR_FRONTEND
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-frontend
    newTag: "9fbc08eb204a503b56f76e249f95e080b844413d"
