apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: your-username-dev

resources:
  - ../../base

images:
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-backend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-backend
    newTag: "7ac452e099c9a200c9d8558f4bc220e590c69cc0"
  - name: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-frontend
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/opsera-se/your-username-frontend
    newTag: "7ac452e099c9a200c9d8558f4bc220e590c69cc0"
