apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ramya-dev

resources:
  - ../../base

images:
  - name: PLACEHOLDER_ECR_BACKEND_URL
    newName: PLACEHOLDER_ECR_BACKEND_URL
    newTag: latest
  - name: PLACEHOLDER_ECR_FRONTEND_URL
    newName: PLACEHOLDER_ECR_FRONTEND_URL
    newTag: latest

# Environment-specific overrides can be added here
# For example, replicas, resource limits, etc.

