apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-username-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/akhilsathwik/prospectf-opsera.git
    targetRevision: HEAD
    path: your-username-opsera/k8s/overlays/dev
  destination:
    # Workload cluster will be registered with ArgoCD and referenced by name
    # The workflow will update this to use the cluster name
    name: opsera-se-usw2-np
    namespace: your-username-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
