apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prospectf500-app1-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akhilsathwik/prospectf-opsera.git
    targetRevision: prospectf500-app1-deploy
    path: k8s-unified/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: prospectf500-app1-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
