apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prospectf500-app1-dev

resources:
  - ../../base

# Image tags will be updated by GitHub Actions workflow
# Placeholders will be replaced: 792373136340 -> actual AWS account ID
images:
  - name: prospectf500-app1-backend
    newName: 792373136340.dkr.ecr.eu-north-1.amazonaws.com/prospectf500-app1-backend
    newTag: b7757be
  - name: prospectf500-app1-frontend
    newName: 792373136340.dkr.ecr.eu-north-1.amazonaws.com/prospectf500-app1-frontend
    newTag: b7757be
