apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prospectf500-app1-dev

resources:
  - ../../base

# Image tags will be updated by GitHub Actions workflow
# ECR registry URLs will be updated automatically during deployment
images:
  - name: prospectf500-app1-backend
    newName: 792373136340.dkr.ecr.eu-north-1.amazonaws.com/prospectf500-app1-backend
    newTag: "e74db07"
  - name: prospectf500-app1-frontend
    newName: 792373136340.dkr.ecr.eu-north-1.amazonaws.com/prospectf500-app1-frontend
    newTag: "e74db07"
